# Generated by Django 3.0.7 on 2020-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_catpcha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
    ]
