# Generated by Django 3.0.7 on 2020-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_catpcha', '0002_api_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha_api',
            name='token_time',
            field=models.DateTimeField(),
        ),
    ]
