# Generated by Django 3.0.7 on 2020-06-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_catpcha', '0003_auto_20200625_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='weixin_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
