# Generated by Django 3.0.7 on 2020-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_catpcha', '0004_captcha_weixin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='captcha_time',
            field=models.DateTimeField(null=True),
        ),
    ]
