# Generated by Django 3.0.7 on 2020-06-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_catpcha', '0005_captcha_captcha_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha_api',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
